name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shop
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && exit 0 || sleep 5
          done
          exit 1

      - name: Run tests with coverage
        run: |
          go test -coverpkg=./... -cover ./...
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: "5432"
          DATABASE_USER: postgres
          DATABASE_PASSWORD: password
          DATABASE_NAME: shop
          GOFLAGS: "-mod=readonly"