on:
  push:
    branches:
      - main
      - dev
  pull_request:

name: Test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run tests
        run: |
          go test -cover ./...
        env:
          GOFLAGS: "-mod=readonly" 
          

    
 
 